# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        none

# Setup
title:            'VPN.ht'
description:      'Regional Gateways and custom OpenVPN Configurations.'
url:              https://config.vpn.ht

author:
  name:           'VPN.ht'

# OpenVPN Configs Available
openvpnConfig:
- country: Europe
  default: /public/files/vpnht-eu.ovpn
  files:
  - name: '64bit'
    url: /public/files/vpnht-eu-64.ovpn
  - name: '128bit'
    url: /public/files/vpnht-eu-128.ovpn
  - name: '256bit'
    url: /public/files/vpnht-eu-256.ovpn
- country: North America
  default: /public/files/vpnht-us.ovpn
  files:
  - name: '64bit'
    url: /public/files/vpnht-us-64.ovpn
  - name: '128bit'
    url: /public/files/vpnht-us-128.ovpn
  - name: '256bit'
    url: /public/files/vpnht-us-256.ovpn
- country: France
  default: /public/files/vpnht-fr.ovpn
  files:
  - name: '64bit'
    url: /public/files/vpnht-fr-64.ovpn
  - name: '128bit'
    url: /public/files/vpnht-fr-128.ovpn
  - name: '256bit'
    url: /public/files/vpnht-fr-256.ovpn
- country: Netherlands
  default: /public/files/vpnht-nl.ovpn
  files:
  - name: '64bit'
    url: /public/files/vpnht-nl-64.ovpn
  - name: '128bit'
    url: /public/files/vpnht-nl-128.ovpn
  - name: '256bit'
    url: /public/files/vpnht-nl-256.ovpn
- country: Deutschland
  default: /public/files/vpnht-de.ovpn
  files:
  - name: '64bit'
    url: /public/files/vpnht-de-64.ovpn
  - name: '128bit'
    url: /public/files/vpnht-de-128.ovpn
  - name: '256bit'
    url: /public/files/vpnht-de-256.ovpn
- country: Nearest
  default: /public/files/vpnht.ovpn
  files:
  - name: '64bit'
    url: /public/files/vpnht-64.ovpn
  - name: '128bit'
    url: /public/files/vpnht-128.ovpn
  - name: '128bit 53 UDP'
    url: /public/files/vpnht-128-53udp.ovpn
  - name: '128bit 443'
    url: /public/files/vpnht-128-port443.ovpn
  - name: '256bit'
    url: /public/files/vpnht-256.ovpn
  - name: '256bit 3389 UDP'
    url: /public/files/vpnht-256-3389udp.ovpn
  - name: '256bit 80'
    url: /public/files/vpnht-256-port80.ovpn
