# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        none

# Setup
title:            'VPN.ht'
description:      'Regional Gateways and custom OpenVPN Configurations.'
url:              http://config.vpn.ht

author:
  name:           'VPN.ht'
